version = 0.1

[staging.deploy.parameters]
stack_name = "cp14-mogo-staging"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
resolve_s3 = true
s3_prefix = "cp14-mogo-staging"
parameter_overrides = "Stage=staging"
no_fail_on_empty_changeset = true
force_upload = true
no_progressbar = true